# Generated by Django 5.2.6 on 2026-02-18 07:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('isbn', models.CharField(help_text='ISBN-13 format', max_length=13, unique=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('total_copies', models.PositiveIntegerField(default=1, help_text='Total copies in library', validators=[django.core.validators.MinValueValidator(1)])),
                ('copies_available', models.PositiveIntegerField(default=1, help_text='Currently available copies (updated on borrow/return)', validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='catalog.author')),
                ('categories', models.ManyToManyField(blank=True, related_name='books', to='catalog.category')),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['isbn'], name='catalog_boo_isbn_43f845_idx'), models.Index(fields=['title'], name='catalog_boo_title_3a1ffe_idx'), models.Index(fields=['copies_available'], name='catalog_boo_copies__f71652_idx')],
            },
        ),
    ]
