# Generated by Django 5.2.6 on 2026-02-18 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='catalog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-borrowed_date'],
                'indexes': [models.Index(fields=['user', 'is_returned'], name='borrowing_b_user_id_c9fb8c_idx'), models.Index(fields=['book', 'is_returned'], name='borrowing_b_book_id_7ee975_idx'), models.Index(fields=['due_date'], name='borrowing_b_due_dat_e330f9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_returned', False)), fields=('user', 'book'), name='unique_active_borrow')],
            },
        ),
    ]
